### ISSUE TITLE
Image build errors with Docker 1.10

### ISSUE THREAD

**Issue by andyp1per** [alexec/docker-maven-plugin#101]
We are getting this on a new slave with Docker 1.10. All works fine on Docker 1.8

[INFO] sha256:ed0ff721c588ba7a1269ccbb367b2b19e795844f56647e036609443961009860
com.github.dockerjava.api.DockerClientException: Could not build image: null
    at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:71)
    at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:48)
    at com.alexecollins.docker.orchestration.DockerOrchestrator.build(DockerOrchestrator.java:360)
    at com.alexecollins.docker.orchestration.DockerOrchestrator.build(DockerOrchestrator.java:299)
    at com.alexecollins.docker.orchestration.DockerOrchestrator.build(DockerOrchestrator.java:829)
    at com.alexecollins.docker.mojo.PackageMojo.doExecute(PackageMojo.java:16)
    at com.alexecollins.docker.mojo.AbstractDockerMojo.execute(AbstractDockerMojo.java:162)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by andyp1per** [comment]
So it looks to me like the problem only occurs with <quiet>true</quiet>. This makes sense to me - I imagine that unless you have verbose on you are not getting the text string you expect back to say the image was created. No idea whether this is a problem in docker, docker-java, the orchestrator or this!

**Comment by alexec** [comment]
I've updated to docker-java:3.0.2 yesterday. Version 2.11.17 should be on Maven Central shortly. Can I please request you see if this fixes this?

**Comment by andyp1per** [comment]
Unfortunately I can't test because of this:
https://github.com/docker-java/docker-java/issues/537
Still shaking my head at the idicoy of it!

**Comment by andyp1per** [comment]
Having sorted out my docker issues on OSX I'm sorry to have to report that this still doesn't work. Its probably something to do with the stdio hijacking they were talking about.
