### ISSUE TITLE
image was not specified

### ISSUE THREAD

**Issue by Thorndike** [alexec/docker-maven-plugin#107]
After Upgrading to docker 1.12.0 I got some weird errors concerning removed options and I upgraded to the latest docker-plugin version 2.11.16 to get around the docker 1.12 problems. Now I receive the following exception:

`[ERROR] Error starting container with id vertragweb: image was not specified
com.alexecollins.docker.orchestration.OrchestrationException: java.lang.NullPointerException: image was not specified
    at com.alexecollins.docker.orchestration.DockerOrchestrator.start(DockerOrchestrator.java:528)
    at com.alexecollins.docker.orchestration.DockerOrchestrator.start(DockerOrchestrator.java:919)
    at com.alexecollins.docker.mojo.StartMojo.doExecute(StartMojo.java:17)
    at com.alexecollins.docker.mojo.AbstractDockerMojo.execute(AbstractDockerMojo.java:164)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.NullPointerException: image was not specified
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
    at com.github.dockerjava.core.command.CreateContainerCmdImpl.<init>(CreateContainerCmdImpl.java:132)
    at com.github.dockerjava.core.DockerClientImpl.createContainerCmd(DockerClientImpl.java:283)
    at com.alexecollins.docker.orchestration.DockerOrchestrator.createNewContainer(DockerOrchestrator.java:662)
    at com.alexecollins.docker.orchestration.DockerOrchestrator.start(DockerOrchestrator.java:501)
    ... 25 more
`

The image is build fine and can be started manually afterwards but the plugin seems to have a problem. Did I miss any configuration changes?

Ubuntu 14.04 LTS
Docker version 1.12.0, build 8eab29e
`<plugin>
                    <groupId>com.alexecollins.docker</groupId>
                    <artifactId>docker-maven-plugin</artifactId>
                    <version>2.11.16</version>
                </plugin>
`

Just tested on an other machine. Exception is also present at 
Docker version 1.11.1, build 5604cbe
CentOS 7.2
It seems I have a problem with the updated plugin version. The configuration was not changes since 2.11.13.

**Comment by alexec** [comment]
I've updated to docker-java:3.0.2 yesterday. Version 2.11.17 should be on Maven Central shortly. Can I please request you test with this new version which has a fix for this.

**Comment by Thorndike** [comment]
Working now on docker 1.11.1 on my CentOS box. On my Ubuntu with docker 1.12.0 I am now back to my initial problem

[ERROR] Unable to start container bf21007dc6156a51088148ab7eed4e17c19f715ffadacb7154d483679bfdc421
com.github.dockerjava.api.exception.BadRequestException: {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}

Is there already an issue for that?

**Comment by mrijke** [comment]
@Thorndike this seems to be a problem in the underlying docker-java library: https://github.com/docker-java/docker-java/issues/617

**Comment by KostyaSha** [comment]
@mrijke wrong reference. HostConfig was fixed in docker-java and error message will be fixed in docker itself. Update this project to use latest docker-java version or switch to NETTY impl.

**Comment by Thorndike** [comment]
Build is working now with Version 2.11.19
