### ISSUE TITLE
Connecting to docker fails (http instead of https; mac + boot2docker)

### ISSUE THREAD

**Issue by arranubels** [alexec/docker-maven-plugin#108]
I get an issue when trying to connect to docker when doing any operation that triggers boot2docker.

Basically, it tries to do a HTTP operation instead of a HTTPS.

Am I doing something wrong or is it a bug with this version?

```
            <plugin>
                <groupId>com.alexecollins.docker</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>2.11.17</version>
                <configuration>
                    <!-- out of the box, you shoud not need to have these, as they'll use sensible defaults -->
                    <!-- (optional) if you want to push to a private repo, all of these are required if using artifactory -->
                    <host>tcp://boot2docker:2376</host>
                    <!-- (optional) if you need to run with configured SSL certificates -->
                    <certificatePath>${user.home}/.boot2docker/certs/default</certificatePath>
                    <!-- (optional) where to same images -->
                    <saveDir>target/docker</saveDir>
                    <!-- (optional) save files to reduce disk space usage -->
                    <gzipSave>false</gzipSave>
                    <!-- (optional) attached saved files for deployment to local repo or Maven repo -->
                    <attach>true</attach>
                    <src>./</src>
                </configuration>
            </plugin>
```

Fails with:
```
[DEBUG] Configuring mojo com.alexecollins.docker:docker-maven-plugin:2.11.17:clean from plugin realm ClassRealm[plugin>com.alexecollins.docker:docker-maven-plugin:2.11.17, parent: sun.misc.Launcher$AppClassLoader@55f96302]
[DEBUG] Configuring mojo 'com.alexecollins.docker:docker-maven-plugin:2.11.17:clean' with basic configurator -->
[DEBUG]   (f) cache = true
[DEBUG]   (f) certificatePath = /Users/arran/.boot2docker/certs/default
[DEBUG]   (f) cleanContainerOnly = false
[DEBUG]   (f) forceClean = false
[DEBUG]   (f) host = tcp://boot2docker:2376
[DEBUG]   (f) permissionErrorTolerant = false
[DEBUG]   (f) prefix = test
[DEBUG]   (f) pull = false
[DEBUG]   (f) quiet = false
[DEBUG]   (f) removeIntermediateImages = false
[DEBUG]   (f) skip = false
[DEBUG]   (f) src = ./
[DEBUG]   (f) username = arran
[DEBUG]   (f) versionAutoDetect = true
[DEBUG]   (f) project = MavenProject: test:1.10-SNAPSHOT @ /Users/arran/Documents/Projects/test/pom.xml
[DEBUG] -- end configuration --
[DEBUG] properties filtering supported for [java.vendor, PWD, sun.java.launcher, sun.management.compiler, EDITOR, PATH, LSCOLORS, os.name, hamcrest.version, sun.boot.class.path, user.country.format, java.vm.specification.vendor, java.runtime.version, MAVEN_CMD_LINE_ARGS, mysql-connector-java.version, project.build.sourceEncoding, user.name, guice.disable.misplaced.annotation.check, SECURITYSESSIONID, JAVA_MAIN_CLASS_9379, user.language, groovy.version, COMMAND_MODE, TMPDIR, sun.boot.library.path, classworlds.conf, project.artifactId, h2.version, java.version, XPC_FLAGS, user.timezone, mail.version, sun.arch.data.model, TERM, xmlworker.version, http.nonProxyHosts, java.endorsed.dirs, ZSH, sun.cpu.isalist, sun.jnu.encoding, file.encoding.pkg, SHELL, file.separator, java.specification.name, java.class.version, org.slf4j.simpleLogger.defaultLogLevel, user.country, java.home, java.vm.info, dynamodblocal.port, os.version, ivy.version, joda-time.version, project.reporting.outputEncoding, path.separator, project.build.finalName, java.vm.version, freemarker.version, SHLVL, java.awt.printerjob, commons-collections.version, sun.io.unicode.encoding, JAVA_HOME, awt.toolkit, MAVEN_PROJECTBASEDIR, LOGNAME, socksNonProxyHosts, ftp.nonProxyHosts, HOME, user.home, XPC_SERVICE_NAME, java.specification.vendor, guava.version, java.library.path, java.vendor.url, commons-beanutils.version, project.description, Apple_PubSub_Socket_Render, java.vm.vendor, gopherProxySet, maven-resources-plugin.version, maven.home, java.runtime.name, sun.java.command, java.class.path, project.version, project.name, java.vm.specification.name, slf4j.version, jgit.version, java.vm.specification.version, sun.cpu.endian, sun.os.patch.level, java.io.tmpdir, java.vendor.url.bug, commons-io.version, OLDPWD, maven.multiModuleProjectDirectory, PAGER, maven-bundle-plugin.version, SSH_AUTH_SOCK, LC_CTYPE, os.arch, java.awt.graphicsenv, super-csv.version, java.ext.dirs, __CF_USER_TEXT_ENCODING, user.dir, log4j.version, line.separator, java.vm.name, xml-apis.version, poi.version, commons-lang3.version, jackson.version, file.encoding, LESS, itextpdf.version, java.specification.version, project.groupId, junit.version, USER]
[DEBUG] Cmd: com.github.dockerjava.jaxrs.VersionCmdExec@2faa55bb
[DEBUG] 1 * Sending client request on thread main
1 > GET http://boot2docker:2376/version
1 > Accept: application/json

[DEBUG] CookieSpec selected: default
[DEBUG] Auth cache not set in the context
[DEBUG] Connection request: [route: {}->http://boot2docker:2376][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
[DEBUG] Connection leased: [id: 0][route: {}->http://boot2docker:2376][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
[DEBUG] Opening connection {}->http://boot2docker:2376
[DEBUG] Connecting to boot2docker/192.168.59.103:2376
[DEBUG] Connection established 192.168.59.3:57553<->192.168.59.103:2376
[DEBUG] Executing request GET /version HTTP/1.1
[DEBUG] Target auth state: UNCHALLENGED
[DEBUG] Proxy auth state: UNCHALLENGED
[DEBUG] http-outgoing-0 >> GET /version HTTP/1.1
[DEBUG] http-outgoing-0 >> Accept: application/json
[DEBUG] http-outgoing-0 >> User-Agent: Jersey/2.23.1 (Apache HttpClient 4.5)
[DEBUG] http-outgoing-0 >> Host: boot2docker:2376
[DEBUG] http-outgoing-0 >> Connection: Keep-Alive
[DEBUG] http-outgoing-0 >> Accept-Encoding: gzip,deflate
[DEBUG] http-outgoing-0 >> "GET /version HTTP/1.1[\r][\n]"
[DEBUG] http-outgoing-0 >> "Accept: application/json[\r][\n]"
[DEBUG] http-outgoing-0 >> "User-Agent: Jersey/2.23.1 (Apache HttpClient 4.5)[\r][\n]"
[DEBUG] http-outgoing-0 >> "Host: boot2docker:2376[\r][\n]"
[DEBUG] http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
[DEBUG] http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
[DEBUG] http-outgoing-0 >> "[\r][\n]"
[DEBUG] http-outgoing-0 << "[0x15][0x3][0x1][0x0][0x2][0x2][\n]"
[DEBUG] Garbage in response: 
[DEBUG] http-outgoing-0 << "end of stream"
[DEBUG] http-outgoing-0: Close connection
[DEBUG] http-outgoing-0: Shutdown connection
[DEBUG] Connection discarded
[DEBUG] http-outgoing-0: Close connection
[DEBUG] Connection released: [id: 0][route: {}->http://boot2docker:2376][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
javax.ws.rs.ProcessingException: org.apache.http.client.ClientProtocolException
        at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
        at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:420)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:316)
        at com.github.dockerjava.jaxrs.VersionCmdExec.execute(VersionCmdExec.java:26)
        at com.github.dockerjava.jaxrs.VersionCmdExec.execute(VersionCmdExec.java:13)
        at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
        at com.alexecollins.docker.mojo.AbstractDockerMojo.dockerClient(AbstractDockerMojo.java:234)
        at com.alexecollins.docker.mojo.AbstractDockerMojo.execute(AbstractDockerMojo.java:162)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.http.client.ClientProtocolException
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
        at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
        ... 37 more
Caused by: org.apache.http.ProtocolException: The server failed to respond with a valid HTTP response
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:151)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        ... 39 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 31.304 s
[INFO] Finished at: 2016-09-12T15:59:57+10:00
[INFO] Final Memory: 29M/237M
[INFO] ------------------------------------------------------------------------

```

With versions;
```
➜  ~ boot2docker version 
Boot2Docker-cli version: v1.8.0
Git commit: 9a26066
➜  ~ docker --host=tcp://boot2docker:2376 --tls --tlsverify --tlscacert=$HOME/.boot2docker/certs/default/ca.pem --tlscert=$HOME/.boot2docker/certs/default/cert.pem --tlskey=$HOME/.boot2docker/certs/default/key.pem version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      linux/amd64
```

Note boot2docker is setup in my /etc/hosts
```
➜  ~ grep boot2docker /etc/hosts
192.168.59.103 boot2docker
```

**Comment by hypery2k** [comment]
you can solve this with socat:
```
brew install socat
```
Then create a launchd-daemon (docker.socat_launcher.plist):
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>docker.socat_launcher</string>
        <key>Disabled</key>
        <false/>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <true/>
        <key>ProgramArguments</key>
        <array>
            <string>/usr/local/bin/socat</string>
            <string>-d</string>
            <string>TCP-LISTEN:2375,range=127.0.0.1/32,reuseaddr,fork</string>
            <string>UNIX:/var/run/docker.sock</string>
        </array>
        <key>StandardErrorPath</key>
    	<string>/Library/Logs/socat_docker.log</string>
    	<key>StandardOutPath</key>
    	<string>/Library/Logs/socat_docker.log</string>
        <key>StartInterval</key>
       <integer>30</integer>
    </dict>
</plist>
```
Then add the entry:
```
cp docker.socat_launcher.plist /Library/LaunchDaemons
sudo launchctl load /Library/LaunchDaemons/docker.socat_launcher.plist
sudo launchctl load docker.socat_launcher.plist
```
Then you can use it:
```
mvn ...  -Ddocker.host=http://127.0.0.1:2375
```
