### ISSUE TITLE
Build failed if Image without tag exists

### ISSUE THREAD

**Issue by Thorndike** [alexec/docker-maven-plugin#109]
Using docker-maven-plugin:2.11.17 my build failed with 

`[INFO] Stopping singlesearchmock
[INFO] Stopping singlesearchmock
[INFO] Cleaning container singlesearchmock
java.lang.NullPointerException
    at com.alexecollins.docker.orchestration.DockerOrchestrator.findImageId(DockerOrchestrator.java:403)
    at com.alexecollins.docker.orchestration.DockerOrchestrator.cleanImage(DockerOrchestrator.java:248)
    at com.alexecollins.docker.orchestration.DockerOrchestrator.clean(DockerOrchestrator.java:238)
    at com.alexecollins.docker.orchestration.DockerOrchestrator.clean(DockerOrchestrator.java:211)
    at com.alexecollins.docker.orchestration.DockerOrchestrator.clean(DockerOrchestrator.java:198)
    at com.alexecollins.docker.orchestration.DockerOrchestrator.clean(DockerOrchestrator.java:185)
    at com.alexecollins.docker.mojo.CleanMojo.doExecute(CleanMojo.java:33)
    at com.alexecollins.docker.mojo.AbstractDockerMojo.execute(AbstractDockerMojo.java:164)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
`

It turned out that docker images was showing an image without TAG information.
`docker-registry.cp.creditreform.de/dev-env/php56_apache        <none>                        dc000b018f7f        12 weeks ago        696 MB
`
Aftar manually tagging that image with TAG info the build worked fine.

**Comment by alexec** [comment]
Hi,

I believe you've found a workaround?

Alex

**Comment by Thorndike** [comment]
One can manually tag the images and build will work.
