### ISSUE TITLE
NPE with Docker 1.6.2 on Circle CI

### ISSUE THREAD

**Issue by tkrille** [alexec/docker-maven-plugin#70]
Hello Alex,

the Docker version on Circle CI (1.4) has some issues pulling images from the Hub, so we switched to Docker 1.6.2 using this stanza in our `circle.yml`:

```yaml
machine:
  pre:
    - sudo curl -L -o /usr/bin/docker 'http://s3-external-1.amazonaws.com/circle-downloads/docker-1.6.2-circleci'; sudo chmod 0755 /usr/bin/docker; true
```

But using the latest Docker version causes a `NullPointerException`:

```
[ERROR] Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.8.4:start (start-docker-container) on project integration-tests: null: MojoExecutionException: NullPointerException -> [Help 1]
```

Here comes the stack trace:

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.8.4:clean (clean-docker-images) on project integration-tests: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException
	at com.alexecollins.docker.mojo.AbstractDockerMojo.execute(AbstractDockerMojo.java:144)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.NullPointerException
	at java.util.Arrays$ArrayList.<init>(Arrays.java:2842)
	at java.util.Arrays.asList(Arrays.java:2828)
	at com.alexecollins.docker.orchestration.Repo.findContainers(Repo.java:98)
	at com.alexecollins.docker.orchestration.DockerOrchestrator.clean(DockerOrchestrator.java:140)
	at com.alexecollins.docker.orchestration.DockerOrchestrator.clean(DockerOrchestrator.java:126)
	at com.alexecollins.docker.mojo.CleanMojo.doExecute(CleanMojo.java:16)
	at com.alexecollins.docker.mojo.AbstractDockerMojo.execute(AbstractDockerMojo.java:142)
	... 21 more
```

This is one of the failing builds: https://circleci.com/gh/tkrille/osiam-connector4java-integration-tests/53. And this is the stuff we try to run on Circle: https://github.com/tkrille/osiam-connector4java-integration-tests/tree/docker-1.6.2. Version of `docker-maven-plugin`: 2.9.2

**Comment by alexec** [comment]
Do you think you could take a look at this:

https://github.com/alexec/docker-maven-plugin/blob/master/circle.yml

**Comment by tkrille** [comment]
I took a look, but I really don't see the obvious mistake I made that you want to point me at. Meanwhile I noticed, that I posted the wrong exception. Here's the right one

```
Caused by: java.lang.NullPointerException
	at java.util.Arrays$ArrayList.<init>(Arrays.java:2842)
	at java.util.Arrays.asList(Arrays.java:2828)
	at com.alexecollins.docker.orchestration.DockerOrchestrator.findContainers(DockerOrchestrator.java:219)
	at com.alexecollins.docker.orchestration.DockerOrchestrator.findAllContainers(DockerOrchestrator.java:212)
	at com.alexecollins.docker.orchestration.DockerOrchestrator.findContainer(DockerOrchestrator.java:393)
	at com.alexecollins.docker.orchestration.DockerOrchestrator.start(DockerOrchestrator.java:355)
	at com.alexecollins.docker.orchestration.DockerOrchestrator.start(DockerOrchestrator.java:659)
	at com.alexecollins.docker.mojo.StartMojo.doExecute(StartMojo.java:17)
	at com.alexecollins.docker.mojo.AbstractDockerMojo.execute(AbstractDockerMojo.java:148)
	... 21 more
```

and also the right link to the failing build: https://circleci.com/gh/tkrille/osiam-connector4java-integration-tests/57

**Comment by tkrille** [comment]
I will read your code to track this issue down.

**Comment by tkrille** [comment]
Oddly enough, it works on my machine. Seems like the adjusted Docker version of Circle CI behaves a little bit different than a vanilla Docker 1.6.2 when it comes to enumerate all present containers?

**Comment by tkrille** [comment]
Ohhhh, I get it. We use `DOCKER_HOST: http://localhost:2375`, but it's actually `DOCKER_HOST: tcp://127.0.0.1:2375` like you did it in you `circle.yml` (minus the TLS part). I'll try to fix this and run another build.

**Comment by tkrille** [comment]
Nope, that didn't do the trick. I think I have to start remote debugging the issue.

**Comment by tkrille** [comment]
So, this is what I found out so far:

When running the Maven build, a strange container gets created. Here's the stripped output of `docker ps -a --no-trunc`:

```
CONTAINER ID                                                       IMAGE                                                                     COMMAND                                                                                       CREATED             STATUS                      PORTS               NAMES
[...]
07de677e6b83ee38ea590710f18c773a01bee4c2774603e1ab410ee989bc89fc   d5b54455d4beb33667b4aa214dc03d683b914a1e24f3de22502ed55fef52aa8f:latest   "/bin/sh -c 'cp -p /usr/share/zoneinfo/Etc/UTC /etc/localtime'"                               10 minutes ago      Dead                                                                 
```

This container has no name. So `com.github.dockerjava.api.model.Container#getNames` returns `null`, which in turn is fed into `Arrays#asList`, which will cause the NPE at `com.alexecollins.docker.orchestration.DockerOrchestrator#findContainers(DockerOrchestrator.java:219)`. I really don't know what's up with this container. It's definitely an intermediate layer created during image building. Seems like a Bug for the Circle CI guys. But in the meantime, are OK with hardening this part of `docker-java-orchestration`, i.e. ignore the container if it has no name? Then I will create a PR for this.

**Comment by tkrille** [comment]
Here's some information from the guys of Circle CI:

> I talked with the person responsible for patching Docker. We don't touch anything related to naming. We think it might be something that happens when trying to remove a container - the removal fails and the system ends up in a bad state.  Like you said, this shouldn't happen under normal conditions.

I'll try to set `removeIntermediateImages` to false to workaround this. In the meantime, please review my PR :)

**Comment by tkrille** [comment]
Update: With `removeIntermediateImages` set to false it works.
